services:
- type: web
  name: streamlit-app
  env: python
  build:
    command: pip install -r requirements.txt
  command: streamlit run app.py # replace app.py with your filename
  routes:
    - path: /
  envVars:
    - key: PYTHONUNBUFFERED
      value: 'true'
